version: "3.6"

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: dev
    image: "$PROJECT_NAME"
    container_name: "${PROJECT_NAME}_app"
    working_dir: /home/app
    volumes:
      - ../:/home/app
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - app-network
    volumes:
      - ./nginx/:/etc/nginx/conf.d

networks:
  app-network:
    driver: bridge
